version: '3'

services:
  mongodb:
    container_name: mongotest
    image: mongodb
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017

  webserver:
    container_name: flasktest
    image: webserver
    depends_on:
      - mongodb
    ports:
      - 5000:5000
    # Additional configuration for the webserver container

  automl:
    container_name: automltest
    image: automl
    depends_on:
      - mongodb
    # Additional configuration for the AutoML container

volumes:
  mongodb_data:
