version: '3'

services:
  mongodb:
    container_name: mymongo
    image: mongodb
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017


  automl:
    container_name: automl
    image: automl
    depends_on:
      - mongodb
    ports:
      - 8000:8000
    volumes:
      - "C:/Users/ayesha.amjad/Documents/GitHub/BigDataProject/MLOPS/Project/automl:/app" 
    command: python train.py


  webserver:
    container_name: flask
    image: webserver
    depends_on:
      - mongodb
      - automl
    ports:
      - 5000:5000
    volumes:
      - "C:/Users/ayesha.amjad/Documents/GitHub/BigDataProject/MLOPS/Project/webserver:/app"  

  webpage:
    container_name: streamlit
    image: webpage
    depends_on:
      - mongodb
      - automl
      - webserver
    ports:
      - 8501:8501
    entrypoint:
      - bash
    volumes:
      - "C:/Users/ayesha.amjad/Documents/GitHub/BigDataProject/MLOPS/Project/webpage:/app"

volumes:
  mongodb_data:
